-- 0083_semantic_core.sql — Noema Grid semantic substrate.
--
-- The semantic core is canonical knowledge, not a derived search cache. It stores
-- logical sources, immutable source versions/regions, entities, claims, claim
-- instances, assessments, explicit unknowns, and projection bindings.
--
-- Sticky invariant: semantic reads MUST still authorize against the LIVE Tela
-- space_access relation. No semantic row carries permissions. space_id is
-- intentionally duplicated through child tables so PostgreSQL itself rejects
-- cross-space references.

-- Existing parent tables need composite uniqueness so semantic rows can use
-- (id, space_id) foreign keys and prevent tenant-crossing references.
CREATE UNIQUE INDEX IF NOT EXISTS idx_pages_id_space
    ON pages(id, space_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_space_files_id_space
    ON space_files(id, space_id);

CREATE TABLE sem_sources (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id      BIGINT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    kind          TEXT NOT NULL CHECK (kind IN ('tela_page','tela_file','url','manual')),
    page_id       BIGINT,
    space_file_id BIGINT,
    uri           TEXT,
    title         TEXT NOT NULL DEFAULT '',
    metadata      JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_by    BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at    TEXT NOT NULL DEFAULT tela_now(),
    updated_at    TEXT NOT NULL DEFAULT tela_now(),
    CHECK (num_nonnulls(page_id, space_file_id, uri) = 1),
    CHECK ((kind = 'tela_page') = (page_id IS NOT NULL)),
    CHECK ((kind = 'tela_file') = (space_file_id IS NOT NULL)),
    CHECK ((kind IN ('url','manual')) = (uri IS NOT NULL)),
    UNIQUE (id, space_id),
    FOREIGN KEY (page_id, space_id) REFERENCES pages(id, space_id) ON DELETE CASCADE,
    FOREIGN KEY (space_file_id, space_id) REFERENCES space_files(id, space_id) ON DELETE CASCADE
);
CREATE INDEX idx_sem_sources_space ON sem_sources(space_id);
CREATE UNIQUE INDEX idx_sem_sources_page
    ON sem_sources(space_id, page_id) WHERE page_id IS NOT NULL;
CREATE UNIQUE INDEX idx_sem_sources_file
    ON sem_sources(space_id, space_file_id) WHERE space_file_id IS NOT NULL;
CREATE UNIQUE INDEX idx_sem_sources_uri
    ON sem_sources(space_id, uri) WHERE uri IS NOT NULL;

CREATE TABLE sem_source_versions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id            BIGINT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    source_id           BIGINT NOT NULL,
    content_hash        TEXT NOT NULL,
    native_revision_ref TEXT,
    content_text        TEXT,
    observed_at         TEXT NOT NULL DEFAULT tela_now(),
    mime                TEXT,
    byte_size           BIGINT,
    metadata            JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at          TEXT NOT NULL DEFAULT tela_now(),
    UNIQUE (id, space_id),
    UNIQUE (source_id, content_hash),
    FOREIGN KEY (source_id, space_id) REFERENCES sem_sources(id, space_id) ON DELETE CASCADE,
    CHECK (byte_size IS NULL OR byte_size >= 0)
);
CREATE INDEX idx_sem_source_versions_source ON sem_source_versions(source_id, observed_at);

CREATE TABLE sem_source_regions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id          BIGINT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    source_version_id BIGINT NOT NULL,
    locator_kind      TEXT NOT NULL,
    locator           JSONB NOT NULL DEFAULT '{}'::jsonb,
    excerpt           TEXT NOT NULL DEFAULT '',
    excerpt_hash      TEXT NOT NULL,
    created_at        TEXT NOT NULL DEFAULT tela_now(),
    UNIQUE (id, space_id),
    UNIQUE (source_version_id, locator_kind, locator, excerpt_hash),
    FOREIGN KEY (source_version_id, space_id) REFERENCES sem_source_versions(id, space_id) ON DELETE CASCADE
);
CREATE INDEX idx_sem_source_regions_version ON sem_source_regions(source_version_id);
CREATE INDEX idx_sem_source_regions_space ON sem_source_regions(space_id);

CREATE TABLE sem_entities (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id        BIGINT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    kind            TEXT NOT NULL CHECK (kind IN ('person','organization','place','event','concept','object','work','other')),
    canonical_name  TEXT NOT NULL,
    description     TEXT NOT NULL DEFAULT '',
    external_ids    JSONB NOT NULL DEFAULT '{}'::jsonb,
    props           JSONB NOT NULL DEFAULT '{}'::jsonb,
    state           TEXT NOT NULL DEFAULT 'active' CHECK (state IN ('active','merged','deprecated')),
    merged_into     BIGINT,
    embedding       vector(1024),
    embedding_model TEXT,
    search_tsv      tsvector GENERATED ALWAYS AS (
        to_tsvector('simple', canonical_name || ' ' || description)
    ) STORED,
    created_by      BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at      TEXT NOT NULL DEFAULT tela_now(),
    updated_at      TEXT NOT NULL DEFAULT tela_now(),
    UNIQUE (id, space_id),
    CHECK ((state = 'merged') = (merged_into IS NOT NULL)),
    CHECK (merged_into IS NULL OR merged_into <> id),
    FOREIGN KEY (merged_into, space_id) REFERENCES sem_entities(id, space_id) ON DELETE RESTRICT
);
CREATE INDEX idx_sem_entities_space_kind ON sem_entities(space_id, kind) WHERE state = 'active';
CREATE INDEX idx_sem_entities_name ON sem_entities(space_id, lower(canonical_name));
CREATE INDEX idx_sem_entities_fts ON sem_entities USING GIN(search_tsv);

CREATE TABLE sem_entity_aliases (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id         BIGINT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    entity_id        BIGINT NOT NULL,
    alias            TEXT NOT NULL,
    normalized_alias TEXT NOT NULL,
    source_region_id BIGINT,
    confidence       DOUBLE PRECISION,
    created_by       BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at       TEXT NOT NULL DEFAULT tela_now(),
    UNIQUE (entity_id, normalized_alias),
    FOREIGN KEY (entity_id, space_id) REFERENCES sem_entities(id, space_id) ON DELETE CASCADE,
    FOREIGN KEY (source_region_id, space_id) REFERENCES sem_source_regions(id, space_id) ON DELETE SET NULL (source_region_id),
    CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1))
);
CREATE INDEX idx_sem_entity_alias_lookup ON sem_entity_aliases(space_id, normalized_alias);

CREATE TABLE sem_claims (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id          BIGINT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    canonical_text    TEXT NOT NULL,
    claim_type        TEXT NOT NULL DEFAULT 'fact' CHECK (claim_type IN ('fact','hypothesis','inference','definition','prediction')),
    predicate         TEXT,
    claim_fingerprint TEXT,
    valid_from        DATE,
    valid_to          DATE,
    time_precision    TEXT,
    time_note         TEXT NOT NULL DEFAULT '',
    qualifiers        JSONB NOT NULL DEFAULT '{}'::jsonb,
    state             TEXT NOT NULL DEFAULT 'active' CHECK (state IN ('active','merged','deprecated')),
    merged_into       BIGINT,
    embedding         vector(1024),
    embedding_model   TEXT,
    search_tsv        tsvector GENERATED ALWAYS AS (
        to_tsvector('simple', canonical_text || ' ' || COALESCE(predicate, ''))
    ) STORED,
    importance        DOUBLE PRECISION,
    uncertainty       DOUBLE PRECISION,
    marginal_yield    DOUBLE PRECISION,
    steward_state     TEXT NOT NULL DEFAULT 'done' CHECK (steward_state IN ('pending','running','done','error','deferred')),
    steward_trigger   TEXT,
    steward_context   JSONB NOT NULL DEFAULT '{}'::jsonb,
    steward_attempts  INTEGER NOT NULL DEFAULT 0,
    steward_error     TEXT,
    stewarded_at      TEXT,
    created_by        BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at        TEXT NOT NULL DEFAULT tela_now(),
    updated_at        TEXT NOT NULL DEFAULT tela_now(),
    UNIQUE (id, space_id),
    CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from),
    CHECK ((state = 'merged') = (merged_into IS NOT NULL)),
    CHECK (merged_into IS NULL OR merged_into <> id),
    CHECK (importance IS NULL OR (importance >= 0 AND importance <= 1)),
    CHECK (uncertainty IS NULL OR (uncertainty >= 0 AND uncertainty <= 1)),
    CHECK (marginal_yield IS NULL OR (marginal_yield >= 0 AND marginal_yield <= 1)),
    CHECK (steward_attempts >= 0),
    FOREIGN KEY (merged_into, space_id) REFERENCES sem_claims(id, space_id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX idx_sem_claims_fingerprint
    ON sem_claims(space_id, claim_fingerprint)
    WHERE claim_fingerprint IS NOT NULL AND state = 'active';
CREATE INDEX idx_sem_claims_space_predicate ON sem_claims(space_id, predicate) WHERE state = 'active';
CREATE INDEX idx_sem_claims_fts ON sem_claims USING GIN(search_tsv);
CREATE INDEX idx_sem_claims_steward ON sem_claims(steward_state, importance, uncertainty, marginal_yield)
    WHERE steward_state IN ('pending','running');

CREATE TABLE sem_claim_slots (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id     BIGINT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    claim_id     BIGINT NOT NULL,
    role         TEXT NOT NULL,
    ordinal      INTEGER NOT NULL DEFAULT 0,
    entity_id    BIGINT,
    literal      JSONB,
    literal_kind TEXT,
    created_at   TEXT NOT NULL DEFAULT tela_now(),
    UNIQUE (claim_id, role, ordinal),
    FOREIGN KEY (claim_id, space_id) REFERENCES sem_claims(id, space_id) ON DELETE CASCADE,
    FOREIGN KEY (entity_id, space_id) REFERENCES sem_entities(id, space_id) ON DELETE RESTRICT,
    CHECK (ordinal >= 0),
    CHECK (num_nonnulls(entity_id, literal) = 1),
    CHECK ((literal IS NULL) = (literal_kind IS NULL))
);
CREATE INDEX idx_sem_claim_slots_entity ON sem_claim_slots(space_id, entity_id) WHERE entity_id IS NOT NULL;
CREATE INDEX idx_sem_claim_slots_role ON sem_claim_slots(space_id, role);

CREATE TABLE sem_claim_instances (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id                BIGINT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    claim_id                BIGINT NOT NULL,
    source_region_id        BIGINT NOT NULL,
    original_text           TEXT NOT NULL,
    proposed_canonical_text TEXT NOT NULL DEFAULT '',
    context                 TEXT NOT NULL DEFAULT '',
    stance                  TEXT NOT NULL DEFAULT 'affirms' CHECK (stance IN ('affirms','denies')),
    extraction_confidence   DOUBLE PRECISION,
    speaker                 TEXT,
    publication             TEXT,
    source_date             DATE,
    deep_link               TEXT,
    created_by              TEXT NOT NULL DEFAULT 'manual',
    created_at              TEXT NOT NULL DEFAULT tela_now(),
    UNIQUE (claim_id, source_region_id, stance),
    FOREIGN KEY (claim_id, space_id) REFERENCES sem_claims(id, space_id) ON DELETE CASCADE,
    FOREIGN KEY (source_region_id, space_id) REFERENCES sem_source_regions(id, space_id) ON DELETE CASCADE,
    CHECK (extraction_confidence IS NULL OR (extraction_confidence >= 0 AND extraction_confidence <= 1))
);
CREATE INDEX idx_sem_claim_instances_claim ON sem_claim_instances(claim_id, created_at);
CREATE INDEX idx_sem_claim_instances_region ON sem_claim_instances(source_region_id);

CREATE TABLE sem_claim_relations (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id         BIGINT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    from_claim_id    BIGINT NOT NULL,
    to_claim_id      BIGINT NOT NULL,
    relation_type    TEXT NOT NULL CHECK (relation_type IN ('supports','contradicts','qualifies','requires','assumes','specifies','defines','derives_from')),
    reason           TEXT NOT NULL DEFAULT '',
    confidence       DOUBLE PRECISION,
    source_region_id BIGINT,
    created_by       TEXT NOT NULL DEFAULT 'manual',
    created_at       TEXT NOT NULL DEFAULT tela_now(),
    UNIQUE (from_claim_id, to_claim_id, relation_type),
    FOREIGN KEY (from_claim_id, space_id) REFERENCES sem_claims(id, space_id) ON DELETE CASCADE,
    FOREIGN KEY (to_claim_id, space_id) REFERENCES sem_claims(id, space_id) ON DELETE CASCADE,
    FOREIGN KEY (source_region_id, space_id) REFERENCES sem_source_regions(id, space_id) ON DELETE SET NULL (source_region_id),
    CHECK (from_claim_id <> to_claim_id),
    CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1))
);
CREATE INDEX idx_sem_claim_relations_from ON sem_claim_relations(from_claim_id);
CREATE INDEX idx_sem_claim_relations_to ON sem_claim_relations(to_claim_id);

CREATE TABLE sem_assessments (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id       BIGINT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    claim_id       BIGINT NOT NULL,
    status         TEXT NOT NULL CHECK (status IN ('verified','supported','contested','unsupported','contradicted','unknown')),
    confidence     DOUBLE PRECISION,
    credence       DOUBLE PRECISION,
    assessment     TEXT NOT NULL DEFAULT '',
    rationale      TEXT NOT NULL DEFAULT '',
    basis          JSONB NOT NULL DEFAULT '{}'::jsonb,
    model          TEXT,
    trigger        TEXT,
    marginal_yield DOUBLE PRECISION,
    is_current     BOOLEAN NOT NULL DEFAULT TRUE,
    assessed_at    TEXT NOT NULL DEFAULT tela_now(),
    created_by     TEXT NOT NULL DEFAULT 'manual',
    FOREIGN KEY (claim_id, space_id) REFERENCES sem_claims(id, space_id) ON DELETE CASCADE,
    CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
    CHECK (credence IS NULL OR (credence >= 0 AND credence <= 1)),
    CHECK (marginal_yield IS NULL OR (marginal_yield >= 0 AND marginal_yield <= 1))
);
CREATE UNIQUE INDEX idx_sem_assessments_current
    ON sem_assessments(claim_id) WHERE is_current;
CREATE INDEX idx_sem_assessments_history ON sem_assessments(claim_id, assessed_at DESC);

CREATE TABLE sem_gaps (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id             BIGINT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    question             TEXT NOT NULL,
    status               TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','resolved','dismissed')),
    importance           DOUBLE PRECISION,
    related_claim_id     BIGINT,
    related_entity_id    BIGINT,
    resolved_by_claim_id BIGINT,
    context              JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_by           TEXT NOT NULL DEFAULT 'manual',
    created_at           TEXT NOT NULL DEFAULT tela_now(),
    resolved_at          TEXT,
    UNIQUE (id, space_id),
    FOREIGN KEY (related_claim_id, space_id) REFERENCES sem_claims(id, space_id) ON DELETE SET NULL (related_claim_id),
    FOREIGN KEY (related_entity_id, space_id) REFERENCES sem_entities(id, space_id) ON DELETE SET NULL (related_entity_id),
    FOREIGN KEY (resolved_by_claim_id, space_id) REFERENCES sem_claims(id, space_id) ON DELETE SET NULL (resolved_by_claim_id),
    CHECK (importance IS NULL OR (importance >= 0 AND importance <= 1)),
    CHECK ((status = 'resolved') = (resolved_at IS NOT NULL)),
    CHECK (resolved_by_claim_id IS NULL OR status = 'resolved')
);
CREATE INDEX idx_sem_gaps_open ON sem_gaps(space_id, importance DESC) WHERE status = 'open';

CREATE TABLE sem_projections (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id             BIGINT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    name                 TEXT NOT NULL,
    kind                 TEXT NOT NULL CHECK (kind IN ('sheet','graph','timeline','map')),
    spec                 JSONB NOT NULL,
    target_page_id       BIGINT,
    mode                 TEXT NOT NULL DEFAULT 'snapshot' CHECK (mode IN ('snapshot','live')),
    revision             INTEGER NOT NULL DEFAULT 1,
    last_materialized_at TEXT,
    created_by           BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at           TEXT NOT NULL DEFAULT tela_now(),
    updated_at           TEXT NOT NULL DEFAULT tela_now(),
    UNIQUE (id, space_id),
    FOREIGN KEY (target_page_id, space_id) REFERENCES pages(id, space_id) ON DELETE SET NULL (target_page_id)
);
CREATE INDEX idx_sem_projections_space ON sem_projections(space_id, kind);

CREATE TABLE sem_projection_bindings (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id         BIGINT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
    projection_id    BIGINT NOT NULL,
    revision         INTEGER NOT NULL,
    page_id           BIGINT NOT NULL,
    sheet_name        TEXT NOT NULL DEFAULT '',
    cell_ref          TEXT NOT NULL,
    entity_id         BIGINT,
    claim_id          BIGINT,
    source_region_id  BIGINT,
    gap_id            BIGINT,
    display_role      TEXT NOT NULL DEFAULT 'primary',
    materialized_at   TEXT NOT NULL DEFAULT tela_now(),
    UNIQUE (projection_id, revision, page_id, sheet_name, cell_ref, display_role),
    FOREIGN KEY (projection_id, space_id) REFERENCES sem_projections(id, space_id) ON DELETE CASCADE,
    FOREIGN KEY (page_id, space_id) REFERENCES pages(id, space_id) ON DELETE CASCADE,
    FOREIGN KEY (entity_id, space_id) REFERENCES sem_entities(id, space_id) ON DELETE CASCADE,
    FOREIGN KEY (claim_id, space_id) REFERENCES sem_claims(id, space_id) ON DELETE CASCADE,
    FOREIGN KEY (source_region_id, space_id) REFERENCES sem_source_regions(id, space_id) ON DELETE CASCADE,
    FOREIGN KEY (gap_id, space_id) REFERENCES sem_gaps(id, space_id) ON DELETE CASCADE,
    CHECK (revision >= 1),
    CHECK (num_nonnulls(entity_id, claim_id, source_region_id, gap_id) = 1)
);
CREATE INDEX idx_sem_projection_bindings_projection ON sem_projection_bindings(projection_id, page_id);
CREATE INDEX idx_sem_projection_bindings_claim ON sem_projection_bindings(claim_id) WHERE claim_id IS NOT NULL;
